import Head from "next/head"
import Aside from "./aside"
import Header from "./header"
import PageIndicator from "./page-indicator"
import { useRouter } from "next/router"

export default function Layout({ children }) {
    const router = useRouter()
    const capitalizeFirstChar = (string) => string.charAt(0).toUpperCase() + string.slice(1)
    const pageName = router.pathname.substring(1) || 'home'
    return (
        <>
            <Head>
                <title>{capitalizeFirstChar(pageName)} | Novian D Syahrizal</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/images/logo.png" />
            </Head>
            <Header />
            <main>
                <Aside />
                {children}
                <PageIndicator />
            </main>
        </>
    )
}
