import Head from "next/head"
import Aside from "./aside"
import Header from "./header"
import PageIndicator from "./page-indicator"

export default function Layout({ children }) {
    return (
        <>
            <Head>
                <title>Novian D Syahrizal | Front-End Developer</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/images/logo.png" />
            </Head>
            <Header />
            <main>
                <Aside />
                {children}
                <PageIndicator />
            </main>
        </>
    )
}
